# Generated by Django 5.0.2 on 2026-08-22 22:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Property_Name",
                    models.CharField(max_length=200, verbose_name="title"),
                ),
                ("slug", models.SlugField(blank=True, max_length=240, unique=True)),
                ("Property_Description", models.TextField(blank=True, default="")),
                (
                    "Total_area_in_sqft",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "Price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly service charge, on top of the rent.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "security_deposit_months",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(24)],
                    ),
                ),
                ("negotiable", models.BooleanField(default=False)),
                (
                    "Property_Pictures",
                    models.ImageField(blank=True, null=True, upload_to="pics"),
                ),
                ("Road_No", models.CharField(blank=True, default="", max_length=10)),
                (
                    "Block",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="block or sector",
                    ),
                ),
                (
                    "City",
                    models.CharField(
                        choices=[
                            ("Dhaka", "Dhaka"),
                            ("Chattogram", "Chattogram"),
                            ("Sylhet", "Sylhet"),
                            ("Khulna", "Khulna"),
                            ("Rajshahi", "Rajshahi"),
                        ],
                        default="Dhaka",
                        max_length=100,
                    ),
                ),
                ("Postal_code", models.CharField(blank=True, default="", max_length=6)),
                (
                    "Area",
                    models.CharField(
                        choices=[
                            ("Gulshan", "Gulshan"),
                            ("Banani", "Banani"),
                            ("Dhanmondi", "Dhanmondi"),
                            ("Bashundhara R/A", "Bashundhara R/A"),
                            ("Uttara", "Uttara"),
                            ("Mirpur", "Mirpur"),
                            ("Mohakhali", "Mohakhali"),
                            ("Badda", "Badda"),
                            ("Motijheel", "Motijheel"),
                            ("Agrabad", "Agrabad"),
                            ("Zindabazar", "Zindabazar"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("landmark", models.CharField(blank=True, default="", max_length=120)),
                (
                    "Property_on",
                    models.CharField(
                        choices=[("rent", "Rent"), ("sale", "Sale")],
                        default="rent",
                        max_length=20,
                    ),
                ),
                (
                    "Property_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("land", "Land"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "furnishing",
                    models.CharField(
                        choices=[
                            ("unfurnished", "Unfurnished"),
                            ("semi", "Semi furnished"),
                            ("full", "Fully furnished"),
                        ],
                        default="unfurnished",
                        max_length=12,
                    ),
                ),
                ("available_from", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("rented", "Rented or sold"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "Approval_by_Agent",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("needs_approval", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "Property_Documents",
                    models.FileField(
                        blank=True,
                        help_text="Ownership paper or deed. Only you and a verified agent can open it.",
                        null=True,
                        upload_to="property_documents",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("icon", models.CharField(default="✔", max_length=8)),
                ("group", models.CharField(default="General", max_length=30)),
            ],
            options={
                "verbose_name_plural": "amenities",
                "ordering": ["group", "name"],
            },
        ),
        migrations.CreateModel(
            name="CommercialProperty",
            fields=[
                (
                    "allproperty_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="property.allproperty",
                    ),
                ),
                ("House_No", models.CharField(blank=True, default="", max_length=10)),
                (
                    "Business_type",
                    models.CharField(
                        choices=[
                            ("office", "Office"),
                            ("community_center", "Community centre"),
                            ("shop", "Shop"),
                            ("restaurant", "Restaurant"),
                            ("warehouse", "Warehouse"),
                            ("other", "Other"),
                        ],
                        default="office",
                        max_length=20,
                    ),
                ),
                ("Parking_spaces", models.PositiveIntegerField(default=0)),
                (
                    "Has_elevator",
                    models.BooleanField(default=False, verbose_name="has a lift"),
                ),
                (
                    "Has_security_system",
                    models.BooleanField(default=False, verbose_name="has security"),
                ),
                (
                    "Has_conference_room",
                    models.BooleanField(
                        default=False, verbose_name="has a conference room"
                    ),
                ),
                (
                    "has_generator",
                    models.BooleanField(default=False, verbose_name="has a generator"),
                ),
                (
                    "Year",
                    models.DateField(blank=True, null=True, verbose_name="built in"),
                ),
            ],
            options={
                "verbose_name_plural": "commercial properties",
            },
            bases=("property.allproperty",),
        ),
        migrations.CreateModel(
            name="LandProperty",
            fields=[
                (
                    "allproperty_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="property.allproperty",
                    ),
                ),
                (
                    "Land_type",
                    models.CharField(
                        choices=[
                            ("Farmland", "Farmland"),
                            ("Playground", "Playground"),
                            ("warehouse", "Warehouse plot"),
                            ("residential_plot", "Residential plot"),
                            ("commercial_plot", "Commercial plot"),
                        ],
                        default="residential_plot",
                        max_length=100,
                    ),
                ),
                (
                    "Road_size_in_sqft",
                    models.PositiveIntegerField(
                        default=0, verbose_name="road width in feet"
                    ),
                ),
                (
                    "Is_fenced",
                    models.BooleanField(default=False, verbose_name="is fenced"),
                ),
                ("has_water_connection", models.BooleanField(default=False)),
                ("has_gas_connection", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "land properties",
            },
            bases=("property.allproperty",),
        ),
        migrations.CreateModel(
            name="ResidentialProperty",
            fields=[
                (
                    "allproperty_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="property.allproperty",
                    ),
                ),
                ("House_No", models.CharField(blank=True, default="", max_length=10)),
                (
                    "Floor_count",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(200)],
                    ),
                ),
                (
                    "floor_number",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(200)],
                    ),
                ),
                (
                    "Bedrooms",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(30)],
                    ),
                ),
                (
                    "Bathrooms",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MaxValueValidator(30)],
                    ),
                ),
                (
                    "Garage_spaces_Per_Sqft",
                    models.PositiveIntegerField(
                        default=0, verbose_name="garage spaces"
                    ),
                ),
                (
                    "Has_Pool",
                    models.BooleanField(default=False, verbose_name="has a pool"),
                ),
                (
                    "Has_Garden",
                    models.BooleanField(default=False, verbose_name="has a garden"),
                ),
                (
                    "Number_of_Balcony",
                    models.PositiveIntegerField(default=1, verbose_name="balconies"),
                ),
                (
                    "has_lift",
                    models.BooleanField(default=False, verbose_name="has a lift"),
                ),
                (
                    "Year",
                    models.DateField(blank=True, null=True, verbose_name="built in"),
                ),
            ],
            options={
                "verbose_name_plural": "residential properties",
            },
            bases=("property.allproperty",),
        ),
        migrations.AddField(
            model_name="allproperty",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="properties", to="property.amenity"
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=12, unique=True)),
                ("visit_date", models.DateField()),
                ("visit_time", models.TimeField()),
                ("message", models.CharField(blank=True, default="", max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for the owner"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "owner_response",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings_received",
                        to="authentication.userprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="property.allproperty",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings_made",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["visit_date", "visit_time"],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_message_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_owner",
                        to="authentication.userprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="property.allproperty",
                    ),
                ),
                (
                    "renter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations_as_renter",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourites",
                        to="authentication.userprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourited_by",
                        to="property.allproperty",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=2000)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="property.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages_sent",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="pics")),
                ("caption", models.CharField(blank=True, default="", max_length=120)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="property.allproperty",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="PropertyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("comment", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_reviews",
                        to="authentication.userprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="property.allproperty",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "viewed_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_views",
                        to="authentication.userprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_log",
                        to="property.allproperty",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=60)),
                ("query_string", models.CharField(max_length=400)),
                ("alert_enabled", models.BooleanField(default=True)),
                (
                    "last_checked",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="allproperty",
            index=models.Index(
                fields=["status", "-created_at"], name="property_al_status_2ad0f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allproperty",
            index=models.Index(
                fields=["Property_type", "Property_on"],
                name="property_al_Propert_490f12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="allproperty",
            index=models.Index(
                fields=["Area", "City"], name="property_al_Area_ba8d2d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="allproperty",
            index=models.Index(fields=["Price"], name="property_al_Price_3ca9b9_idx"),
        ),
        migrations.AddIndex(
            model_name="allproperty",
            index=models.Index(fields=["slug"], name="property_al_slug_76f1fd_idx"),
        ),
        migrations.AddConstraint(
            model_name="allproperty",
            constraint=models.CheckConstraint(
                check=models.Q(("Price__gte", 0)), name="price_not_negative"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["owner", "status"], name="property_bo_owner_i_ceb54d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["renter", "status"], name="property_bo_renter__031719_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "accepted")),
                fields=("property", "visit_date", "visit_time"),
                name="one_accepted_visit_per_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=("property", "renter", "visit_date", "visit_time"),
                name="no_duplicate_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("property", "renter"), name="one_thread_per_renter_per_property"
            ),
        ),
        migrations.AddConstraint(
            model_name="favourite",
            constraint=models.UniqueConstraint(
                fields=("profile", "property"), name="unique_favourite"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="property_me_convers_be9747_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertyreview",
            index=models.Index(
                fields=["property", "-created_at"],
                name="property_pr_propert_94a2d2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="propertyreview",
            constraint=models.UniqueConstraint(
                fields=("property", "author"), name="one_review_per_person"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyview",
            index=models.Index(
                fields=["property", "viewed_on"], name="property_pr_propert_9ce803_idx"
            ),
        ),
    ]
