# Generated by Django 5.0.2 on 2026-08-23 05:59

import django.core.validators
import property.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allproperty",
            name="Property_Documents",
            field=models.FileField(
                blank=True,
                help_text="Ownership paper or deed. Only you and a verified agent can open it.",
                null=True,
                storage=property.storage.PrivateStorage(),
                upload_to="property_documents",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["pdf", "jpg", "jpeg", "png"]
                    )
                ],
            ),
        ),
    ]
