# Generated by Django 5.0.2 on 2026-09-12 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0002_alter_allproperty_property_documents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amenity",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
    ]
