# Generated by Django 5.0.2 on 2026-09-13 12:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0004_userprofile_is_suspended_userprofile_suspended_at_and_more",
        ),
        ("property", "0003_amenity_icon_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=80)),
                (
                    "query_string",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("hits", models.PositiveIntegerField(default=0)),
                (
                    "searched_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_searches",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-searched_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fake", "The listing looks fake"),
                            ("taken", "Already rented or sold"),
                            ("wrong", "Details or photos are wrong"),
                            ("price", "The price is misleading"),
                            ("duplicate", "Posted more than once"),
                            ("offensive", "Offensive or spam content"),
                            ("other", "Something else"),
                        ],
                        max_length=12,
                    ),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("upheld", "Upheld"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_handled",
                        to="authentication.userprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="property.allproperty",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_filed",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="property_pr_status_4771dd_idx",
                    ),
                    models.Index(
                        fields=["property", "status"],
                        name="property_pr_propert_c289f9_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="propertyreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("property", "reporter"),
                name="one_open_report_per_person_per_listing",
            ),
        ),
        migrations.AddIndex(
            model_name="recentsearch",
            index=models.Index(
                fields=["profile", "-searched_at"],
                name="property_re_profile_da1948_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="recentsearch",
            constraint=models.UniqueConstraint(
                fields=("profile", "term"), name="one_row_per_person_per_term"
            ),
        ),
    ]
