# Generated by Django 5.0.2 on 2026-08-22 22:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("ip", models.CharField(blank=True, default="", max_length=45)),
                ("successful", models.BooleanField(default=False)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["username", "-attempted_at"],
                        name="authenticat_usernam_9e4177_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("contact_no", models.CharField(blank=True, default="", max_length=20)),
                (
                    "gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Male"), (2, "Female"), (3, "Other")],
                        null=True,
                    ),
                ),
                (
                    "nid",
                    models.CharField(blank=True, max_length=18, null=True, unique=True),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, default="")),
                ("bio", models.TextField(blank=True, default="", max_length=500)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_picture"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("renter", "Renter"),
                            ("owner", "Property owner"),
                            ("agent", "Agent"),
                        ],
                        default="renter",
                        max_length=10,
                    ),
                ),
                ("is_agent", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("avatar_color", models.CharField(default="#00B98E", max_length=7)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="UserProfile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("booking", "Booking"),
                            ("message", "Message"),
                            ("approval", "Approval"),
                            ("review", "Review"),
                            ("alert", "Alert"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.CharField(blank=True, default="", max_length=300)),
                ("link", models.CharField(blank=True, default="", max_length=300)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["role"], name="authenticat_role_4d1409_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["is_agent"], name="authenticat_is_agen_c96d00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["profile", "is_read", "-created_at"],
                name="authenticat_profile_509bd5_idx",
            ),
        ),
    ]
