# Generated by Django 5.0.2 on 2026-08-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_avatar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_color',
            field=models.CharField(default='#009C6B', max_length=7),
        ),
    ]
