# Generated by Django 5.0.2 on 2026-08-22 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("reverted", "Sent back for changes"),
                            ("verified", "Documents verified"),
                            ("featured", "Featured"),
                            ("unfeatured", "Unfeatured"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_actions",
                        to="authentication.userprofile",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_actions",
                        to="property.allproperty",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["property", "-created_at"],
                        name="Agents_agen_propert_5e0c49_idx",
                    ),
                    models.Index(
                        fields=["agent", "-created_at"],
                        name="Agents_agen_agent_i_9c2717_idx",
                    ),
                ],
            },
        ),
    ]
