# Generated by Django 5.0.2 on 2026-09-13 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Agents", "0001_initial"),
        (
            "authentication",
            "0004_userprofile_is_suspended_userprofile_suspended_at_and_more",
        ),
        ("property", "0004_recentsearch_propertyreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentaction",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actions_against",
                to="authentication.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="agentaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("reverted", "Sent back for changes"),
                    ("verified", "Documents verified"),
                    ("featured", "Featured"),
                    ("unfeatured", "Unfeatured"),
                    ("rpt_upheld", "Report upheld"),
                    ("rpt_ok", "Report dismissed"),
                    ("suspended", "Account suspended"),
                    ("lifted", "Suspension lifted"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="agentaction",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_actions",
                to="property.allproperty",
            ),
        ),
    ]
